name: mini_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter_native_splash: 2.4.0
  firebase_core: ^2.30.1
  firebase_auth: 4.19.4
  google_fonts: 6.2.1
  cloud_firestore: 4.17.2
  image_picker: 1.1.0
  firebase_storage: 11.7.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 3.0.2
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/logo.png
    - assets/images/login_logo1.png
    - assets/images/Bg-Splash_Screen.png
    - assets/elements/Vector1.png
    - assets/elements/Vector2.png
    - assets/elements/Vector3.png
  uses-material-design: true
